apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service-deployment
spec:
  selector:
    matchLabels:
      app: products-service
  replicas: 2
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - name: products-service
        image: products-service:v4
        ports:
        - containerPort: 8002
