apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    run: products-service
spec:
  type: NodePort
  ports:
  - port: 8002
    protocol: TCP
    name: http
  selector:
    app: products-service