apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    run: products-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  products_service_mapping
      prefix: /products/
      service: products-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8002
    protocol: TCP
  selector:
    app: products-service