apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    run: cart-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  cart_service_mapping
      prefix: /cart/
      service: cart-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
  selector:
    app: cart-service