apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service-deployment
spec:
  selector:
    matchLabels:
      app: cart-service
  replicas: 2
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: cart-service:v1
        ports:
        - containerPort: 8001
